---
pages:
- practice-tests.md
- faq.md
- book.md
- rates.md
- blog/britain-s-musical-journey.md
- blog/william-shakespeare.md
- blog/elizabeth-i.md
- blog/henry-viii.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
